
       

          <!-- Single button -->
        <div class="btn-group">
          <button           
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            Save
          </button>
         
        </div>

          <!-- Single button -->
        <div class="btn-group">
          <button 
          type="button" 
          class="btn btn-default dropdown-toggle " 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
           Save and Close
          </button>
         
        </div>

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href="<?=base_url()?>/"
          type="button" 
          class="btn btn-default dropdown-toggle btn-danger" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
           Cancel
          </a>
         
        </div>

          <h2 class="sub-header">Edit Contact</h2>

          <form action="<?=base_url()?>/editContact/<?=$this->contact["id_contact"]?>" method="POST">
          <div class="form-group">
            <label for="nameInput">Name</label>
            <input type="text" class="form-control" name="nome" id="nameInput" placeholder="Name" value="<?=$this->contact["nome"]?>">
          </div>

          <div class="form-group">
            <label for="phoneInput">Phone</label>
            <input type="text" class="form-control" name="phone" id="phoneInput" placeholder="Email" value="<?=$this->contact["phone"]?>">
          </div>

          <div class="form-group">
            <label for="emailInput">Email address</label>
            <input type="email" class="form-control" id="emailInput"  name="email" placeholder="Email" value="<?=$this->contact["email"]?>">
          </div>
         
          <button type="submit" class="btn btn-default">Save</button>
        </form>
          
     