
          

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href="<?=base_url()?>/cadastro"
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            + Add Phone Number
          </a>
         
        </div>

          <h2 class="sub-header">List Contacts</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>E-mail</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                <?php foreach ($this->contacts as $key) { ?>
                 
               
                <tr>
                  <td><?=$key["nome"]?></td>
                  <td><?=$key["phone"]?></td>
                  <td><?=$key["email"]?></td>
                  <td>
                    <div class="btn-group" role="group">
                      <a type="button" class="btn btn-default btn-primary" href="/editContact/<?=$key["id_contact"]?>">Edit</a>
                       <a type="button" class="btn btn-default btn-danger" href="/deleteContact/<?=$key["id_contact"]?>">Delete</a>
                     
                    </div>
                  </td>                  
                </tr>   
                <?php } ?>             
              </tbody>
            </table>
          </div>
     