
          

          <!-- Single button -->
        <div class="btn-group">
          <a 
          href="<?=base_url()?>/cadastro"
          type="button" 
          class="btn btn-default dropdown-toggle btn-success" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            + Add Phone Number
          </a>
         
        </div>

          <h2 class="sub-header">List Contacts</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Phone</th>
                  <th>E-mail</th>
                  <th>Options</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Felipe</td>
                  <td>(98) 912386-7788</td>
                  <td>dicasdoprogramador@gmail.com</td>
                  <td>
                    <div class="btn-group" role="group">
                      <button type="button" class="btn btn-default btn-primary">Edit</button>
                      <button type="button" class="btn btn-default btn-danger">Delete</button>
                     
                    </div>
                  </td>                  
                </tr>                
              </tbody>
            </table>
          </div>
     